apiVersion: apps/v1                      # API version for Deployment
kind: Deployment                         # Defines a Deployment
metadata:
  name: auth-depl                        # Deployment name
  namespace: development                 # Namespace for deployment
spec:
  replicas: 1                            # Number of pod replicas
  selector:
    matchLabels:
      app: auth                          # Match pods with label app: auth
  template:
    metadata:
      labels:
        app: auth                        # Label for the pod
    spec:
      containers:
        - name: auth                     # Container name
          image: 192.100.40.5:5001/auth  # Image to use (dev-registry)
          env: 
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always        # Always pull latest image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch  # Match node architecture
                operator: In
                values:
                  - amd64                # Only schedule on amd64 nodes
#                  - arm64                # (Optional) Allow arm64 nodes if uncommented
---
apiVersion: v1                           # API version for Service
kind: Service                            # Defines a Service
metadata:
  name: auth-srv                         # Service name
  namespace: development                 # Namespace for service
spec:
  selector:
    app: auth                            # Target pods with label app=auth
  ports:
    - name: auth                         # Port name
      protocol: TCP                      # Protocol to use
      port: 3000                         # Service port
      targetPort: 3000                   # Pod container port
