apiVersion: networking.k8s.io/v1            # API version for Ingress
kind: Ingress                               # Defines an Ingress resource
metadata:
  name: ingress-srv                         # Ingress name
  namespace: development                    # Namespace for ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"             # Enable regex in paths
spec:
  ingressClassName: nginx                   # nginx ingress controller
  rules:
  - host: ticketing.dev                     # Hostname rule applies to
    http:
      paths:
        - path: /api/users/?(.*)            # Match path with optional suffix using regex
          pathType: ImplementationSpecific  # Path interpretation by ingress controller
          backend:
            service:
              name: auth-srv                # Route traffic to this service
              port:
                number: 3000                # Service port to target
        - path: /api/tickets/?(.*)
          pathType: ImplementationSpecific  # Path interpretation by ingress controller
          backend:
            service:
              name: tickets-srv
              port:
                number: 3000
        - path: /api/orders/?(.*)
          pathType: ImplementationSpecific  # Path interpretation by ingress controller
          backend:
            service:
              name: order-srv
              port:
                number: 3000
        - path: /?(.*)            # Match path with optional suffix using regex
          pathType: ImplementationSpecific  # Path interpretation by ingress controller
          backend:
            service:
              name: client-srv                # Route traffic to this service
              port:
                number: 3000                # Service port to target
