apiVersion: apps/v1                      # API version for Deployment
kind: Deployment                         # Defines a Deployment
metadata:
  name: nats-depl                        # Deployment name
  namespace: development                 # Namespace for deployment
spec:
  replicas: 1                            # Number of pod replicas
  selector:
    matchLabels:
      app: nats                          # Match pods with label app: nats
  template:
    metadata:
      labels:
        app: nats                        # Label for the pod
    spec:
      containers:
        - name: nats                     # Container name
          image: nats-streaming:0.17.0  # Image to use (dev-registry)
          args: [
            "-p", "4222", "-m", "8222", "-hbi", "5s", "-hbt", "5s", "-hbf", "2", "-SD", "-cid", "ticketing",      
          ]
          imagePullPolicy: Always        # Always pull latest image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch  # Match node architecture
                operator: In
                values:
                  - amd64                # Only schedule on amd64 nodes
#                  - arm64                # (Optional) Allow arm64 nodes if uncommented
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
  - name: client
    protocol: TCP
    port: 4222
    targetPort: 4222
  - name: monitoring
    protocol: TCP
    port: 8222
    targetPort: 8222
