apiVersion: apps/v1                      # API version for Deployment
kind: Deployment                         # Defines a Deployment
metadata:
  name: orders-depl                        # Deployment name
  namespace: development                 # Namespace for deployment
spec:
  replicas: 1                            # Number of pod replicas
  selector:
    matchLabels:
      app: orders                          # Match pods with label app: orders
  template:
    metadata:
      labels:
        app: orders                        # Label for the pod
    spec:
      containers:
        - name: orders                     # Container name
          image: 192.100.40.5:5001/orders  # Image to use (dev-registry)
          env: 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always        # Always pull latest image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch  # Match node architecture
                operator: In
                values:
                  - amd64                # Only schedule on amd64 nodes
#                  - arm64                # (Optional) Allow arm64 nodes if uncommented
---
apiVersion: v1                           # API version for Service
kind: Service                            # Defines a Service
metadata:
  name: orders-srv                         # Service name
  namespace: development                 # Namespace for service
spec:
  selector:
    app: orders                            # Target pods with label app=orders
  ports:
    - name: orders                         # Port name
      protocol: TCP                      # Protocol to use
      port: 3000                         # Service port
      targetPort: 3000                   # Pod container port
