apiVersion: apps/v1
kind: Deployment
metadata: 
 name: tickets-mongo-depl
 namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch  # Match node architecture
                operator: In
                values:
                  - amd64                # Only schedule on amd64 nodes
#                  - arm64                # (Optional) Allow arm64 nodes if uncommented
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
  namespace: development
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017