apiVersion: apps/v1                      # API version for Deployment
kind: Deployment                         # Defines a Deployment
metadata:
  name: tickets-depl                        # Deployment name
  namespace: development                 # Namespace for deployment
spec:
  replicas: 1                            # Number of pod replicas
  selector:
    matchLabels:
      app: tickets                          # Match pods with label app: tickets
  template:
    metadata:
      labels:
        app: tickets                        # Label for the pod
    spec:
      containers:
        - name: tickets                     # Container name
          image: 192.100.40.5:5001/tickets  # Image to use (dev-registry)
          env: 
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always        # Always pull latest image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch  # Match node architecture
                operator: In
                values:
                  - amd64                # Only schedule on amd64 nodes
#                  - arm64                # (Optional) Allow arm64 nodes if uncommented
---
apiVersion: v1                           # API version for Service
kind: Service                            # Defines a Service
metadata:
  name: tickets-srv                         # Service name
  namespace: development                 # Namespace for service
spec:
  selector:
    app: tickets                            # Target pods with label app=tickets
  ports:
    - name: tickets                         # Port name
      protocol: TCP                      # Protocol to use
      port: 3000                         # Service port
      targetPort: 3000                   # Pod container port
