apiVersion: skaffold/v4beta3    # Skaffold API version
kind: Config                    # Configuration type

manifests:                      # Path to Kubernetes manifests
  rawYaml:
    - ./infra/k3s/*             # Kubernetes YAML files
    
build:
  local:
    push: false                 # Don't push images to the registry
