apiVersion: skaffold/v4beta3          # Skaffold API version
kind: Config                          # Configuration type

manifests:                            # Path to Kubernetes manifests
  rawYaml:
    - ./infra/k8s/*                   # Kubernetes YAML files

build:
  local:
    push: true                        # Push images to registry
    useDockerCLI: true                # Use Docker CLI for builds
    useBuildkit: true                 # Enable BuildKit (for optimizations)
  platforms: ["linux/amd64", "linux/arm64"]  # Build for both AMD64 and ARM64
  tagPolicy:
    sha256: {}                        # Tag images by SHA256 hash

  artifacts:
    - image: 192.100.40.5:5001/auth   # Image name and registry
      context: auth                   # Build context directory
      docker:
        dockerfile: Dockerfile        # Dockerfile location
        buildArgs:
          PLATFORM: "linux/amd64"     # Build argument for platform
      sync:                           # File sync for development
        manual:
          - src: 'src/**/*.ts'        # Files to sync
            dest: .                   # Sync destination
    - image: 192.100.40.5:5001/client   # Image name and registry
      context: client                   # Build context directory
      docker:
        dockerfile: Dockerfile        # Dockerfile location
        buildArgs:
          PLATFORM: "linux/amd64"     # Build argument for platform
      sync:                           # File sync for development
        manual:
          - src: 'src/**/*.ts'        # Files to sync
            dest: .                   # Sync destination
portForward:                          # Local port forwarding
  - resourceType: service             # Forward a Kubernetes service
    resourceName: auth-srv            # Service name
    port: 4000                        # Service port to forward
    localPort: 4000                   # Local port to bind
    namespace: development            # Kubernetes namespace
  - resourceType: service             # MongoDB service port forwarding
    resourceName: auth-mongo-srv      # MongoDB service name from your K8s service
    port: 27017                       # MongoDB port
    localPort: 27017                  # Local port to access MongoDB
    namespace: development            # Kubernetes namespace
  - resourceType: service             # Forward a Kubernetes service
    resourceName: client-srv            # Service name
    port: 3000                        # Service port to forward
    localPort: 3000                   # Local port to bind
    namespace: development            # Kubernetes namespace